### PR TITLE
bump prom2teams to 4.2.1

### PR DESCRIPTION
**Pull request by vardhaman22**
#### Pull Request Checklist ####

- [X] Change does not remove any existing Images or Tags in the images-list file
- [X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ ] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [X] New entries are in format `SOURCE DESTINATION TAG`
- [X] New entries are added to the correct section of the list (sorted lexicographically)
- [X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [X] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####
prom2teams vresion bump

#### Linked Issues ####
https://github.com/rancher/rancher/issues/41504

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Review by rayandas — COMMENTED** [review]
Also add prom2teams in https://github.com/rancher/image-mirror/blob/master/retrieve-image-tags/config.json
Read more on this here: https://github.com/rancher/image-mirror/blob/master/README.md#adding-new-tags-to-existing-images

cc: @superseb

**Comment by vardhaman22** [comment]
> Also add prom2teams in https://github.com/rancher/image-mirror/blob/master/retrieve-image-tags/config.json Read more on this here: https://github.com/rancher/image-mirror/blob/master/README.md#adding-new-tags-to-existing-images
> 
> cc: @superseb

thanks for pointing it out.
updated.

**Comment by rayandas** [comment]
Looks good. Need approval from code owners.

**Review by brandond — APPROVED** [review]

**Comment by rayandas** [comment]
@brandond could you please merge the PR as well?

**Pull request merged**
