### PR TITLE
include fluentd latest base build

### PR DESCRIPTION
**Pull request by jbiers**
#### Pull Request Checklist ####

- [x] Change does not remove any existing Images or Tags in the images-list file
- [x] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [x] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [x] New entries are in format `SOURCE DESTINATION TAG`
- [x] New entries are added to the correct section of the list (sorted lexicographically)
- [x] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [x] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [x] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

New image tag

#### Linked Issues ####

[#1366](https://github.com/rancherlabs/image-scanning/issues/1366)

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Review by mallardduck — CHANGES_REQUESTED** [review]
This LGTM overall - however I have some minor feedback.

We probably want to match the versions of the images with that of upstream.
So we would take the version we mirror from here:

https://github.com/rancher/charts/blob/1cde28a5180fdea1db8fa35dbf1eae73f9bf9547/packages/rancher-logging/package.yaml#L1

And go find the equivalent tag (in this case 4.8.0) on the repo's Github, and find the default they set for the tag version: https://github.com/kube-logging/logging-operator/blob/f8081b7bdbd2622820d2384fbe86b58873dc8db2/pkg/sdk/logging/api/v1beta1/logging_types.go#L175

In this case we see it is set to `v1.16-4.8-full` which is their rolling release tag, so we have to use that to resolve the static tag since this will change. And the current one seems to resolve to [v1.16-4.8-full-build.149](https://github.com/orgs/kube-logging/packages/container/fluentd/245314979?tag=v1.16-4.8-full-build.149)

So that's the value we should use to mirror this image.

Note - might be worth considering what other images we mirror for logging and if we are using the expected versions. Taking steps to properly mirror those might be good too. (i.e. we use rancher/mirrored-jimmidyson-configmap-reload, but should/could probably mirror the same one upstream uses `ghcr.io/kube-logging/config-reloader`)

**Comment by brandond** [comment]
This change LGTM - it sounds like there is some work necessary to pin the specific tag used by the chart though? I'll wait for that conversation to resolve before approving and merging.

**Comment by jbiers** [comment]
> This LGTM overall - however I have some minor feedback.
> 
> We probably want to match the versions of the images with that of upstream. So we would take the version we mirror from here:
> 
> https://github.com/rancher/charts/blob/1cde28a5180fdea1db8fa35dbf1eae73f9bf9547/packages/rancher-logging/package.yaml#L1
> 
> And go find the equivalent tag (in this case 4.8.0) on the repo's Github, and find the default they set for the tag version: https://github.com/kube-logging/logging-operator/blob/f8081b7bdbd2622820d2384fbe86b58873dc8db2/pkg/sdk/logging/api/v1beta1/logging_types.go#L175
> 
> In this case we see it is set to `v1.16-4.8-full` which is their rolling release tag, so we have to use that to resolve the static tag since this will change. And the current one seems to resolve to [v1.16-4.8-full-build.149](https://github.com/orgs/kube-logging/packages/container/fluentd/245314979?tag=v1.16-4.8-full-build.149)
> 
> So that's the value we should use to mirror this image.
> 
> Note - might be worth considering what other images we mirror for logging and if we are using the expected versions. Taking steps to properly mirror those might be good too. (i.e. we use rancher/mirrored-jimmidyson-configmap-reload, but should/could probably mirror the same one upstream uses `ghcr.io/kube-logging/config-reloader`)

I appreciate the thorough explanation, thanks! Just updated the image tag to match the expected one. Also, I'll open a separate issue to further investigate the use of mirrored images for logging as suggested.

**Review by mallardduck — APPROVED** [review]
🚢

**Review by brandond — APPROVED** [review]

**Comment by jbiers** [comment]
@brandond I might need some help with merging this when you're available :D

Also, the [DockerHub repo](https://hub.docker.com/r/rancher/mirrored-kube-logging-fluentd) for this image seems to not have any deployed tags even though we already had one in entry for it in the image-list file. Do you know what might be the reason?

**Comment by brandond** [comment]
https://github.com/rancher/image-mirror/actions/runs/10574628248/job/29296558931#step:8:3621
```
time="2024-08-27T09:02:52Z" level=fatal msg="writing blob: initiating layer upload to /v2/rancher/mirrored-kube-logging-fluentd/blobs/uploads/ in registry-1.docker.io: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
===
Failed copying image for rancher/mirrored-kube-logging-fluentd
===
```

It looks like EIO has not granted the bot account access to publish to that repo. That should probably be fixed before we add additional tags.

cc @dharmit 
* https://github.com/rancherlabs/eio/issues/2369

**Pull request merged**
