### PR TITLE
Update grafana images to 9.2.10, 9.3.6

### PR DESCRIPTION
**Pull request by ebuildy**
#### Pull Request Checklist ####

- [x] Change does not remove any existing Images or Tags in the images-list file
- [x] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [x] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [x] New entries are in format `SOURCE DESTINATION TAG`
- [x] New entries are added to the correct section of the list (sorted lexicographically)
- [x] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [x] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

version bump

#### Final Checks after the PR is merged ####
- [x] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Comment by brandond** [comment]
Are we OK to do this? For some reason I thought we were unable to distribute the newer AGPL-licensed versions of Grafana.

**Comment by ebuildy** [comment]
I saw there is already grafana 9.1 in the list

**Comment by superseb** [comment]
@prachidamle @aiyengar2 Can you share what the intended plan is for Grafana in monitoring chart? And wether we want to allow mirroring monitoring/grafana images without a charts update.

**Comment by brijesh310** [comment]
Hi @superseb ,

Kindly update the image tage to 9.3.6
Because in grafana image tag below 9.2.4 there are multiple high vulnerabilities. And if this commit not pushed. Can you let me know the way to ugrade the the rancher monitoring grafana with latest tag 9.3.6 ?

Awaiting you reply

**Comment by superseb** [comment]
@brijesh310 Just merging this PR only mirrors the new images, but it does not update the chart(s) to use the newly mirrored images. That is why the PR is assigned to @prachidamle and @aiyengar2 to make sure the correct steps are taken based on what the plan is for the chart(s).

**Pull request closed without merging**
