### PR TITLE
Add rpardini/docker-registry-proxy:0.6.1

### PR DESCRIPTION
**Pull request by brandond**
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

#### Pull Request Checklist ####

- [X] Change does not remove any existing Images or Tags
- [X] New entries are in format `SOURCE DESTINATION TAG`
- [X] New entries are added to the correct section of the list (sorted lexographically) 

#### Types of Change ####

New image

#### Linked Issues ####

k3s-io/k3s#2686

#### Additional Notes ####

Repo does not currently exist

### CODE REVIEW

**Review by cbron — COMMENTED** [review]
Looks fine once repo exists.

**Comment by brandond** [comment]
I forget, who has access to create repos? @deniseschannon ?

**Comment by cbron** [comment]
@brandond I'll ping you

**Review by aiyengar2 — APPROVED** [review]
LGTM once repo is created

**Pull request merged**
