### PR TITLE
[Blocked on Rebase] Update images for monitoring rebase

### PR DESCRIPTION
**Pull request by aiyengar2**
Related PR: https://github.com/rancher/charts/pull/641

### CODE REVIEW

**Review by deniseschannon — CHANGES_REQUESTED** [review]
I believe you're supposed to add new lines to the file going forward instead of replacing the image tags of existing lines. Is that right @brandond and @Oats87?

**Comment by cjellick** [comment]
yeah, can @brandond and/or @Oats87 be required reviewers on this repo?

**Comment by cjellick** [comment]
also, we're on the verge of merging a big script refactor. lets rebase this after that

**Comment by aiyengar2** [comment]
Closing out this PR in favor of https://github.com/rancher/image-mirror/pull/35.

**Pull request closed without merging**
