### PR TITLE
Add Prometheus Operator v0.39.0 images

### PR DESCRIPTION
**Pull request by aiyengar2**
#### Pull Request Checklist ####

- [x] Change does not remove any existing Images or Tags
- [x] New entries are in format `SOURCE DESTINATION TAG`
- [x] New entries are added to the correct section of the list (sorted lexographically) 
- [x] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

New images, but the repositories for both already exist:
- https://hub.docker.com/r/rancher/coreos-prometheus-operator
- https://hub.docker.com/r/rancher/coreos-prometheus-config-reloader

#### Linked Issues ####

Related Issue: https://github.com/rancher/rancher/issues/29149
Related PR: https://github.com/rancher/system-charts/pull/345

### CODE REVIEW

**Comment by aiyengar2** [comment]
> New images, but the repositories for both already exist:
> - https://hub.docker.com/r/rancher/coreos-prometheus-operator
> - https://hub.docker.com/r/rancher/coreos-prometheus-config-reloader

Not sure if this requires any special consideration with the current state of the scripts; if we merge this PR, will it disturb the existing images in those repos? The older versions of these images are currently used by Monitoring V1 (and will continue to be used for Monitoring V2 since only V1 is upgrading to v0.39.0).

cc: @brandond @PennyScissors

**Comment by PennyScissors** [comment]
> > New images, but the repositories for both already exist:
> > 
> > * https://hub.docker.com/r/rancher/coreos-prometheus-operator
> > * https://hub.docker.com/r/rancher/coreos-prometheus-config-reloader
> 
> Not sure if this requires any special consideration with the current state of the scripts; if we merge this PR, will it disturb the existing images in those repos? The older versions of these images are currently used by Monitoring V1 (and will continue to be used for Monitoring V2 since only V1 is upgrading to v0.39.0).
> 
> cc: @brandond @PennyScissors

I don't think it would cause any issues because v1 gatekeeper uses an older tag of the same image as v2 gatekeeper, so as long as they were pushed once it should fine. However, v2 gatekeeper uses a different repo now since before we made big changes in image-list so I'm not sure if any of those new changes could cause problems. @brandond might be able to confirm.

**Review by brandond — APPROVED** [review]
Looks to me like they're new tags for both, so LGTM

**Review by cbron — APPROVED** [review]

**Comment by aiyengar2** [comment]
Thanks for the approvals! However, I'm holding off on merging this till https://github.com/rancher/system-charts/pull/345#issuecomment-698650663 is addressed.

**Comment by aiyengar2** [comment]
https://github.com/rancher/rancher/issues/29149#issuecomment-699138151

**Pull request closed without merging**
