### PR TITLE
Add missing cilium-operator image

### PR DESCRIPTION
**Pull request by pjbgf**
#### Pull Request Checklist ####

- [x] Change does not remove any existing Images or Tags in the images-list file
- [x] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [x] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [x] New entries are in format `SOURCE DESTINATION TAG`
- [x] New entries are added to the correct section of the list (sorted lexicographically)
- [x] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [x] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [x] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

This image is currently referenced by two charts but does not exist: 
https://github.com/rancher/rke2-charts/blob/83d8960812f14bb459d28eb873312ed3294dc180/packages/rke2-cilium/generated-changes/patch/values.yaml.patch#L119

https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-cilium-legacy/charts/values.yaml#L12-L13

#### Additional Notes ####

Added all existing cilium tags, to ensure users stuck on older version of the charts would be able to enable the operator, if they so wish.

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Review by superseb — COMMENTED** [review]
@rbrtbnfgl Any info you have on this or was this just missed?

@pjbgf Are `v1.12.4` and `v1.12.5` the only ones actively in use? Do we not need earlier versions?

**Comment by pjbgf** [comment]
It looks like it was just missed, the other variants `cilium/operator-{generic,aws,gke}` are all OK.

`v1.12.4` is currently in use (in the chart) and `v1.12.5` is what I am bumping it to. 
Alternatively we could pull all the versions the other cilium images as being used, just in case someone is caught on an older version of the chart.

**Comment by pjbgf** [comment]
After some digging, I found other references to earlier versions:
https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-cilium-legacy/charts/values.yaml#L12-L13

Will update this PR accordingly.

**Comment by rbrtbnfgl** [comment]
The RKE2 chart on the latest version is using the `1.12.4` version. We don't need to mirror the operator because the chart will use the generic image.

**Comment by brandond** [comment]
@rbrtbnfgl if I am understanding your comment, we don't need to mirror these?

**Comment by pjbgf** [comment]
I installed cilium on rke2 and it did pick up the generic version of the operator. 

@rbrtbnfgl I am assuming the same applies for the legacy chart: https://github.com/rancher/rke2-charts/blob/main-source/packages/rke2-cilium-legacy/charts/values.yaml#L12-L13

If so, feel free to just close the PR and I will update the other PR that refers to this.

**Comment by brandond** [comment]
Yes, you can see where it builds the full image name at https://github.com/rancher/rke2-charts/blob/3fd16c7524207ccf52062d2dde318e706e8e1b2d/charts/rke2-cilium-legacy/rke2-cilium/1.11.101/charts/cilium/templates/cilium-operator/_helpers.tpl#L28-L31 - there is always some suffix on it.

**Comment by pjbgf** [comment]
Nice one, thank you for checking I completely missed that. Closing this issue.

**Pull request closed without merging**
