### PR TITLE
Correct neuvector prometheus exporter mirror image name

### PR DESCRIPTION
**Pull request by garyduan**
#### Pull Request Checklist ####

- [ X] Change does not remove any existing Images or Tags in the images-list file
- [ X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X] New entries are in format `SOURCE DESTINATION TAG`
- [ X] New entries are added to the correct section of the list (sorted lexicographically)
- [ X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ X] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [ X] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Comment by selvamt94** [comment]
@brandond Can you please check this PR, not sure where it is failed. We want to release Rancher feature chart with these images.

**Comment by brandond** [comment]
@selvamt94 CI should show you why/where it failed: https://drone-pr.rancher.io/rancher/image-mirror/637/1/2

Looks like the new image is not in the correct place in the list; entries must be properly sorted.

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
LGTM once CI is green. Have you opened a ticket with EIO to request setup of the new repository on Docker Hub?

> `ERROR: Docker Hub namespace rancher and repository mirrored-neuvector-registry-adapter does not exist`

**Comment by brandond** [comment]
I restarted CI, lets confirm that it passes, then I can merge.

**Pull request merged**
