### PR TITLE
Bump up neuvector product version to 5.2.1

### PR DESCRIPTION
**Pull request by garyduan**
#### Pull Request Checklist ####

- [ X] Change does not remove any existing Images or Tags in the images-list file
- [ X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X] New entries are in format `SOURCE DESTINATION TAG`
- [ X] New entries are added to the correct section of the list (sorted lexicographically)
- [ X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ ] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [ ] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
Looks like some of the source tags don't exist yet?

**Comment by selvamt94** [comment]
> Looks like some of the source tags don't exist yet?

I created PR to remove them, looks like it got merged. Are you refering this?
https://github.com/rancher/image-mirror/pull/434

**Comment by brandond** [comment]
No, I'm referring to the CI failure.

```
Checking if image neuvector/prometheus-exporter:5.2.1 exists
time="2023-08-25T00:47:13Z" level=fatal msg="Error parsing image name \"docker://neuvector/prometheus-exporter:5.2.1\": Error reading manifest 5.2.1 in docker.io/neuvector/prometheus-exporter: manifest unknown: manifest unknown"
ERROR: Image neuvector/prometheus-exporter:5.2.1 does not exist
```

**Comment by selvamt94** [comment]
> docker.io/neuvector/prometheus-exporter

It is available now, can you please check again
`neuvector@ubuntu1604-Helm:~/actions-runner/_work/scripts/scripts$ docker pull docker.io/neuvector/prometheus-exporter:5.2.1
5.2.1: Pulling from neuvector/prometheus-exporter
7264a8db6415: Pull complete
eb8686346886: Pull complete
817b5e10e7c1: Pull complete
Digest: sha256:ba28ae8ca0bc02fe4e533bdee81676c3e518ded982c30e5d45b92264129c3930
Status: Downloaded newer image for neuvector/prometheus-exporter:5.2.1
docker.io/neuvector/prometheus-exporter:5.2.1
`

**Review by brandond — APPROVED** [review]

**Comment by selvamt94** [comment]
> I can re-run CI, sure.

Can you please merge too, I need to create PR for Rancher chart.

**Pull request merged**
