### PR TITLE
Remove deprecated longhorn CSI images

### PR DESCRIPTION
**Pull request by innobead**
Signed-off-by: David Ko <dko@suse.com>

#### Pull Request Checklist ####

- [x] Change does not remove any existing Images or Tags in the images-list file
- [x] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [x] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ ] New entries are in format `SOURCE DESTINATION TAG`
- [ ] New entries are added to the correct section of the list (sorted lexicographically)
- [ ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

Remove duplicated and deprecated Longhorn CSI images. 

#### Linked Issues ####

N/A

#### Additional Notes ####

N/A

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Comment by innobead** [comment]
cc @yangchiu @shuo-wu

**Review by shuo-wu — COMMENTED** [review]
I saw the comment you left in the Slack channel but it was still unclear to me. Can you explain a little bit more?

Do you mean all images with the prefix `rancher/mirrored-longhornio` or `rancher/longhornio` will be removed? Then will it affect Longhorn v1.2.0 installation?

**Comment by innobead** [comment]
> I saw the comment you left in the Slack channel but it was still unclear to me. Can you explain a little bit more?
> 
> Do you mean all images with the prefix `rancher/mirrored-longhornio` or `rancher/longhornio` will be removed? Then will it affect Longhorn v1.2.0 installation?

No, they will not be removed, because there are duplicated recent versions of CSI image copies (`rancher/longhornio-csi-*` and `rancher/mirrored-longhornio-csi-*`). We will only keep ones from `longhornio` dockerhub registry instead.

caused by: https://github.com/rancher/image-mirror/commit/980e6edfbb4c882dcffc8bb4eea3b99a68d91f54

**Comment by shuo-wu** [comment]
I see. There are duplicates
```
k8s.gcr.io/sig-storage/csi-attacher rancher/longhornio-csi-attacher v3.2.1
k8s.gcr.io/sig-storage/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1
......
longhornio/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1
```

Just curious, why not retain `k8s.gcr.io/sig-storage/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1`? In the newer version, we will directly use the official images in `k8s.gcr.io/sig-storage`. Does `longhornio/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1` contain the fix for the arm64 while the official one does not?

**Comment by innobead** [comment]
> I see. There are duplicates
> 
> ```
> k8s.gcr.io/sig-storage/csi-attacher rancher/longhornio-csi-attacher v3.2.1
> k8s.gcr.io/sig-storage/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1
> ......
> longhornio/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1
> ```
> 
> Just curious, why not retain `k8s.gcr.io/sig-storage/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1`? In the newer version, we will directly use the official images in `k8s.gcr.io/sig-storage`. Does `longhornio/csi-attacher rancher/mirrored-longhornio-csi-attacher v3.2.1` contain the fix for the arm64 while the official one does not?

The context is here https://github.com/longhorn/longhorn/issues/3258. I think finally we chose to keep the same user experience for users to do less change in values.yaml as usual to deploy Longhorn in an air-gap environment w/ the private registry provided only w/o requiring updating each CSI image repository, but the cons is what I mentioned in the issue.

Actually, the images are the same but just mirrored from the upstream. cc @PhanLe1010 @yangchiu

**Comment by shuo-wu** [comment]
OK. I was thinking we will switch back to using the official images after the upstream fixes the arm64 issues. My bad... Then this removal LGTM

**Review by shuo-wu — APPROVED** [review]

**Review by cbron — APPROVED** [review]
Confirmed all these images and versions still exist in the list, and are coming from non gcr registry.

**Pull request merged**
