### PR TITLE
Added new image node-driver-registrar for calico

### PR DESCRIPTION
**Pull request by rbrtbnfgl**
#### Pull Request Checklist ####

- [ ] Change does not remove any existing Images or Tags in the images-list file
- [ ] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ ] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ ] New entries are in format `SOURCE DESTINATION TAG`
- [ ] New entries are added to the correct section of the list (sorted lexicographically)
- [ ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ ] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [ ] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

This adds the new image for calico needed for the csi-node-driver

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

### CODE REVIEW

**Review by manuelbuil — APPROVED** [review]

**Comment by brandond** [comment]
@rbrtbnfgl did you disable this in the chart so it's no longer necessary, or do we still need it?

**Comment by manuelbuil** [comment]
We need it just in case the users enable it in the helm chart values. The Dockerhub project is now created by EIO, so CI should pass. Let me restart

**Comment by manuelbuil** [comment]
can't restart CI, can you do it @Anarkis ?

**Comment by rbrtbnfgl** [comment]
There is another image that needs to be mirrored.

**Comment by rbrtbnfgl** [comment]
@brandond I disabled it on the chart so we don't need them by default. We probably need to mirror the images in case someone enables it.

**Review by brandond — CHANGES_REQUESTED** [review]
You need to open a request with EIO to create the target repo and allow the bot to push to it.
```
rancher/mirrored-calico-csi is a new target repository
Checking if Docker Hub namespace rancher and repository mirrored-calico-csi exists
ERROR: Docker Hub namespace rancher and repository mirrored-calico-csi does not exist
```

**Comment by rbrtbnfgl** [comment]
The repo should be already created

**Comment by brandond** [comment]
I've restarted CI to see if it will pass now.

**Review by brandond — APPROVED** [review]

**Pull request merged**
